name: Generate Contribution Nebula

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Contribution Graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ShakeebSk
          outputs: |
            dist/github-contribution-grid-nebula.svg?palette=github-dark&color_snake=#FF6FD8&color_dots=#0D1117,#1a1a2e,#16213e,#533483,#FF6FD8
            
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
